//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameCenterCore.Implementation.Persistance
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    internal partial class MainPersistanceEntities : DbContext
    {
        public MainPersistanceEntities()
            : base("name=MainPersistanceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        internal DbSet<User> Users { get; set; }
        internal DbSet<webpages_Membership> webpages_Membership { get; set; }
        internal DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        internal DbSet<webpages_Roles> webpages_Roles { get; set; }
        internal DbSet<Party> Parties { get; set; }
        internal DbSet<Player> Players { get; set; }
    }
}
