//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameCenterCore.Implementation.Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartyDb
    {
        public PartyDb()
        {
            this.Players = new HashSet<PlayerDb>();
        }
    
        public System.Guid Id { get; set; }
        public short StatusId { get; set; }
        public System.Guid GameId { get; set; }
        public Nullable<System.DateTime> UpdatedDateUTC { get; set; }
        public string Version { get; set; }
        public string Data { get; set; }
    
        public virtual ICollection<PlayerDb> Players { get; set; }
    }
}
