//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameCenterCore.Implementation.Persistance
{
    using System;
    using System.Collections.Generic;
    
    internal partial class Party
    {
        public Party()
        {
            this.Players = new HashSet<Player>();
        }
    
        public long Id { get; set; }
    
        public virtual ICollection<Player> Players { get; set; }
    }
}
