//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameCenterCore.Implementation.Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerDb
    {
        public System.Guid Id { get; set; }
        public int UserId { get; set; }
        public System.Guid PartyId { get; set; }
        public Nullable<byte> Szin { get; set; }
        public string ConnectionId { get; set; }
        public string Nick { get; set; }
        public byte ClientStatus { get; set; }
    
        public virtual PartyDb Party { get; set; }
        public virtual UserDb User { get; set; }
    }
}
