//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameCenterCore.Implementation.Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDb
    {
        public UserDb()
        {
            this.Players = new HashSet<PlayerDb>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Nick { get; set; }
    
        public virtual ICollection<PlayerDb> Players { get; set; }
    }
}
